In [2]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
print(x)
print(x[::]) # whole
print(x[5:]) # 5th index onward
print(x[:7]) # till 6th index
print(x[2:9]) # 2nd to 8th index
print(x[2:9:2]) # 2nd to 8th index increment by 2

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]
[3 5 7 9]


In [3]:
x=np.arange(0,10,0.2) # increment by 0.2
print(x)
y=np.linspace(0,10,5) # divide 0 to 10 in 20 equal partition
print(y)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
[ 0.   2.5  5.   7.5 10. ]


In [12]:
x=np.array([[1,2,3,4],[3,4,5,6]])
print(x)
print(x.shape)
print('Dimension=',len(x.shape))
###### slicing
print(x[1:3,2:4])
print(x[:,2])
print(x[1,:])

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)
Dimension= 2
[[5 6]]
[3 5]
[3 4 5 6]


In [15]:
######## increase and decrease dimension
a=np.expand_dims(x,axis=0) # axis 0,1,2 already (2,4)
print(a.shape)
b=np.squeeze(a,axis=0) # delete extra dimension value=1
print(b.shape)

(1, 2, 4)
(2, 4)


In [4]:
##### special matrix
a=np.zeros((3,4))
b=np.ones((4,5))
# Random
c=np.random.random() # single value
print(c)
d=np.random.random((2,5)) # 2x5 matrix
print(d)
e=np.random.randint(0,100) # random integer inbetween 0 to 100
print(e)
f=np.random.randint(0,100,(2,5))# random integer inbetween 0 to 100 of shape 2 x5
print(f)

0.36264131011331946
[[0.01820398 0.36970852 0.47501903 0.80607207 0.62410163]
 [0.75481513 0.24383323 0.02581171 0.34531861 0.85707376]]
61
[[79 20 45 13 91]
 [39 66  9 35 52]]


In [9]:
np.random.choice([1,2,3,4])
np.random.shuffle([1,2,3,4])
np.random.seed(123)

In [25]:
# numpy operations
a=np.random.randint(0,100,(3,3))
b=np.random.randint(0,40,(3,3))
print(a+b) # matrix addition
print(a-b) # matrix substraction
print(2*a) # multiply by 2
print(a*b) # element by elemet multiplication
print(np.dot(a,b)) # dot product
print(a.dot(b)) # dot product
print(a**3) # a to poer 3
print(a%3) # modulo by 3

[[ 98 115  57]
 [ 91 110 100]
 [ 43  73  77]]
[[68 83 -7]
 [53 54 82]
 [25 65 23]]
[[166 198  50]
 [144 164 182]
 [ 68 138 100]]
[[1245 1584  800]
 [1368 2296  819]
 [ 306  276 1350]]
[[3351 4200 4222]
 [3457 3812 5499]
 [2271 2676 3059]]
[[3351 4200 4222]
 [3457 3812 5499]
 [2271 2676 3059]]
[[571787 970299  15625]
 [373248 551368 753571]
 [ 39304 328509 125000]]
[[2 0 1]
 [0 1 1]
 [1 0 2]]


In [10]:
# numpy functions
a=np.random.randint(0,100,(2,2))
print(a)
print('Total Sum',np.sum(a))
print('Sum column wise',np.sum(a,axis=0))
print('Sum row wise',np.sum(a,axis=1))
# similirly for mean,max,std,var etc
print(np.argmax(a)) # return maximum index
print(np.argmax(a,axis=1)) # return maximum index in row
print(np.argmax(a,axis=0)) # return maximum index in col

[[66 92]
 [98 17]]
Total Sum 273
Sum column wise [164 109]
Sum row wise [158 115]
2
[1 0]
[1 0]


In [29]:
np.exp(1)
np.sqrt(2)
np.std([1,2,3,4,5,6,7])
np.mean([1,2,3,4,5,6,7])
np.var([1,2,3,4,5,6,7])
np.median([1,2,3,4,5,6,7])

4.0

In [31]:
x=[1,2,3,4,5,6,7]
np.array(x)

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
import numpy as np
a,b=np.unique([1,2,1,2,1,2,3,4],return_counts=True)
print(a)
print(b)

[1 2 3 4]
[3 3 1 1]
